import './globals.css'
import type { Metadata } from 'next'
import { Chakra_Petch } from 'next/font/google'
import ThemeProvider from './providers/NextThemeProvider'
import PiwikProWrapper from './providers/PiwikProProvider'

const chakra_petch = Chakra_Petch({weight: "400", subsets: ["latin"]})

export const metadata: Metadata = {
  title: 'Arma 3 HTML Preset Merger',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={chakra_petch.className}>
      <PiwikProWrapper>
        <ThemeProvider>
            {children}
        </ThemeProvider>
      </PiwikProWrapper>
      </body>
    </html>
  )
}
